<Project>

	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<IsTrimmable>false</IsTrimmable>
		<EnableTrimAnalyzer>false</EnableTrimAnalyzer>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<NoWarn>$(NoWarn); NETSDK1138</NoWarn>

		<CoverletOutputFormat>opencover</CoverletOutputFormat>
		<CoverletOutput>$(MSBuildThisFileDirectory)TestResults/$(AssemblyName)/$(TargetFramework)/</CoverletOutput>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.msbuild">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions"/>
		<PackageReference Include="JunitXml.TestLogger"/>
		<PackageReference Include="Microsoft.NET.Test.Sdk"/>
		<PackageReference Include="Newtonsoft.Json"/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="FluentAssertions"/>
		<Using Include="FluentAssertions.Execution"/>
		<Using Include="FluentAssertions.Equivalency"/>
	</ItemGroup>

</Project>
