name: Run tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-dotnet@v2.1.0
      - run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /nologo /clp:NoSummary

      - name: Run Tests
        run: >
          dotnet test
          -p:CollectCoverage=true
          -p:CoverletOutput=TestResults/
          -p:CoverletOutputFormat=opencover
          --configuration Release
          --no-build

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.2.3
        with:
          solution: PaperlessDotNet.sln

      - name: Gather Code Coverage
        if: github.event.schedule == null
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true
