name: Run tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    environment: Testing

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore /warnAsError /nologo /clp:NoSummary

      - name: Run Tests
        run: >
          dotnet test
          -p:CollectCoverage=true
          -p:BuildInParallel=true
          -m:8
          --configuration Release
          --no-build
          --logger:"junit;LogFilePath=TestResults/test-result.junit.xml"
        env:
          Paperless__BaseAddress: 'https://localhost:5002/'
          Paperless__Token: 'token'

      - name: Gather Code Coverage
        if: github.event.schedule == null
        uses: codecov/codecov-action@v5.3.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Gather Test Results
        uses: codecov/test-results-action@v1.0.1
        if: always()
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: true

  resharper:
    name: Resharper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.2.0
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore /warnAsError /nologo /clp:NoSummary

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.3.1
        with:
          solution: PaperlessDotNet.sln
          resharper-version: 2023.3.2
          treat-warnings-as-errors: true
